name: GPX_to_Strava

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 * * *'
  push:
    branches:
      - master
    paths:
      - scripts/gpx_to_strava_sync.py
      
env:
  # please change to your own config.
  RUN_TYPE: gpxtostrava 
  ATHLETE: Chongnuo Ji
  TITLE: Run CJ Run
  GITHUB_NAME: hyyz17200
  GITHUB_EMAIL: hyyz172000@gmail.com


jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      # from pdm and install dep
      - name: Set Variables
        id: set_variables
        run: |
          sudo apt-get install libxml2-dev libxslt-dev python3-dev 
          echo "PY=$(python -c 'import hashlib, sys;print(hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest())')" >> $GITHUB_OUTPUT
          echo "PIP_CACHE=$(pip cache dir)" >> $GITHUB_OUTPUT

      - name: Cache PIP
        uses: actions/cache@v2
        with:
          path: ${{ steps.set_variables.outputs.PIP_CACHE }}
          key: Ubuntu-pip-${{ steps.set_variables.outputs.PY }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        if: steps.pip-cache.outputs.cache-hit != 'true'

      - name: Run sync Strava script
        if: env.RUN_TYPE == 'gpxtostrava'
        run: |
          python scripts/gpx_to_strava_sync.py ${client_id} ${client_secret} ${strava_refresh_token} --all
